### ISSUE TITLE
Push f-droid version

### ISSUE THREAD

**Issue by hrehfeld** [Skarafaz/mercury#28]
The version on f-droid is 3 years old: https://f-droid.org/en/packages/it.skarafaz.mercury/

Can you push the current build?

**Comment by Skarafaz** [comment]
All changes have been pushed: both stable and master branches are up to
date.

Il giorno mar 12 nov 2019 alle ore 16:37 Hauke Rehfeld <
notifications@github.com> ha scritto:

**Comment by doronbehar** [comment]
Hey @Skarafaz, this seems to be the issue on F-Droid's side: https://gitlab.com/fdroid/fdroiddata/issues/1801. quoting:

> That's currently still a .txt file, and for v1.2.2 the build block states:
> ```
> disable=lintVitalRelease fails
> ```
> So we cannot build it (relan tried it 2 weeks ago).

Do you understand what that means?

BTW not necessarily related, but I'm experiencing the following error when trying to exchange a public key. Here's the relevant entry from the Log:

```
Algorithm negotiation fail
```

~~Is this fixed in the latest release?~~ Can confirm it is fixed :)

**Comment by Skarafaz** [comment]
> Do you understand what that means?

No, I don't. I'll try to investigate!

**Comment by hrehfeld** [comment]
Any update on this? The version on f-droid is still `Version 1.2.1 (7) - Added on 2016-11-13`

**Comment by Skarafaz** [comment]
> Any update on this? The version on f-droid is still `Version 1.2.1 (7) - Added on 2016-11-13`

This should have been fixed.

**Comment by axelsimon** [comment]
The current version on F-Droid is [Version 1.2.3 Added on 2020-11-03 ](https://f-droid.org/en/packages/it.skarafaz.mercury/). 
@Skarafaz this issue should probably be closed.

**Comment by hrehfeld** [comment]
Thanks!
